otel:
  instrumentation:
    common:
      db:
        query-sanitization:
          enabled: false
    logback-appender:
      experimental:
        capture-code-attributes: true
    http:
      client:
        emit-experimental-telemetry: true
      server:
        emit-experimental-telemetry: true
        capture-request-headers: [key]
  propagators:
    - b3
  resource:
    attributes:
      attributeFromYaml: true # boolean will be automatically converted to string by spring

application:
  prop: propValue
  prop-with-dash: provWithDashValue

spring:
